# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'process.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from gui.res import source_rc

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(732, 607)
        self.lineEdit_in = QtWidgets.QLineEdit(Form)
        self.lineEdit_in.setGeometry(QtCore.QRect(90, 190, 401, 21))
        self.lineEdit_in.setObjectName("lineEdit_in")
        self.pushButton_in = QtWidgets.QPushButton(Form)
        self.pushButton_in.setGeometry(QtCore.QRect(540, 180, 93, 28))
        self.pushButton_in.setObjectName("pushButton_in")
        self.pushButton_out = QtWidgets.QPushButton(Form)
        self.pushButton_out.setGeometry(QtCore.QRect(540, 240, 93, 28))
        self.pushButton_out.setObjectName("pushButton_out")
        self.lineEdit_out = QtWidgets.QLineEdit(Form)
        self.lineEdit_out.setGeometry(QtCore.QRect(90, 250, 401, 21))
        self.lineEdit_out.setObjectName("lineEdit_out")
        self.lineEdit_out_name = QtWidgets.QLineEdit(Form)
        self.lineEdit_out_name.setGeometry(QtCore.QRect(90, 310, 551, 21))
        self.lineEdit_out_name.setObjectName("lineEdit_out_name")
        self.progressBar = QtWidgets.QProgressBar(Form)
        self.progressBar.setGeometry(QtCore.QRect(10, 570, 651, 23))
        self.progressBar.setProperty("value", 24)
        self.progressBar.setObjectName("progressBar")
        self.pushButton_start_cut = QtWidgets.QPushButton(Form)
        self.pushButton_start_cut.setGeometry(QtCore.QRect(280, 480, 93, 28))
        self.pushButton_start_cut.setObjectName("pushButton_start_cut")
        self.radioButton_second = QtWidgets.QRadioButton(Form)
        self.radioButton_second.setGeometry(QtCore.QRect(90, 358, 115, 31))
        self.radioButton_second.setObjectName("radioButton_second")
        self.radioButton_round = QtWidgets.QRadioButton(Form)
        self.radioButton_round.setGeometry(QtCore.QRect(280, 358, 115, 31))
        self.radioButton_round.setObjectName("radioButton_round")
        self.radioButton_all = QtWidgets.QRadioButton(Form)
        self.radioButton_all.setGeometry(QtCore.QRect(480, 358, 115, 31))
        self.radioButton_all.setObjectName("radioButton_all")
        self.lineEdit_start = QtWidgets.QLineEdit(Form)
        self.lineEdit_start.setGeometry(QtCore.QRect(90, 410, 171, 21))
        self.lineEdit_start.setObjectName("lineEdit_start")
        self.lineEdit_end = QtWidgets.QLineEdit(Form)
        self.lineEdit_end.setGeometry(QtCore.QRect(280, 410, 171, 21))
        self.lineEdit_end.setObjectName("lineEdit_end")
        self.lineEdit_num = QtWidgets.QLineEdit(Form)
        self.lineEdit_num.setGeometry(QtCore.QRect(470, 410, 161, 21))
        self.lineEdit_num.setObjectName("lineEdit_num")
        self.pushButton_fork = QtWidgets.QPushButton(Form)
        self.pushButton_fork.setGeometry(QtCore.QRect(690, 10, 31, 28))
        self.pushButton_fork.setStyleSheet("border-image: url(:/img/close_fill.png);")
        self.pushButton_fork.setText("")
        self.pushButton_fork.setObjectName("pushButton_fork")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.pushButton_in.setText(_translate("Form", "输入路径"))
        self.pushButton_out.setText(_translate("Form", "输出路径"))
        self.pushButton_start_cut.setText(_translate("Form", "开始裁切"))
        self.radioButton_second.setText(_translate("Form", "指定帧截取"))
        self.radioButton_round.setText(_translate("Form", "范围截取"))
        self.radioButton_all.setText(_translate("Form", "全部截取"))



if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
